experiment:
  run_name: "detector_dev"
  output_dir: "runs"
  seed: 42

dataset:
  name: "uae_license_plate"
  root: "data/processed/unified"
  image_dir: "images"
  label_dir: "labels"
  split_train: "data/splits/train.txt"
  split_val: "data/splits/val.txt"
  image_size: [512, 512]
  letterbox_color: [114, 114, 114]
  class_names: ["license_plate"]
  max_targets_per_image: 1  # Set >1 to train/evaluate on multiple plates per image
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  augmentations:
    geometric:
      scale_range: [0.5, 1.5]
      aspect_ratio: [0.9, 1.1]
      translate: 0.1
      rotation: 7.0
      shear: 5.0
      perspective: 0.02
    photometric:
      brightness: 0.2
      contrast: 0.2
      hsv_h: 5.0
      hsv_s: 0.2
      hsv_v: 0.2
    degradations:
      motion_blur:
        kernel: [3, 7]
      gaussian_blur_sigma: 1.2
      gaussian_noise_sigma: 0.01
      jpeg_quality: [40, 90]
      sharpening: 0.05
    occlusion:
      cutout:
        patches: 3
        max_size: 0.1
      edge_occlusion_probability: 0.1

model:
  name: "yolov8n"  # Options: toy_cnn, yolov5n, yolov8n, yolov10n, rtdetr_tiny, pp_picodet_s
  num_classes: 1

training:
  epochs: 120
  batch_size: 8
  num_workers: 4
  lr: 0.002
  weight_decay: 0.0005
  betas: [0.9, 0.999]
  grad_clip_norm: 1.0
  warmup_epochs: 3
  cosine_final_ratio: 0.1
  amp: true
  ema_decay: 0.9999
  qat_start_epoch: 84  # final 30% of training

loss:
  lambda_box: 2.0
  lambda_l1: 1.0
  lambda_cls: 1.0
  focal_alpha: 0.25
  focal_gamma: 2.0

evaluation:
  score_threshold: 0.25
  map_thresholds: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
  small_box_area: 0.05

quantization:
  backend: "fbgemm"
  qat:
    enable: true
    start_ratio: 0.7
  ptq:
    max_batches: 50
